# Generated by Django 4.0.6 on 2022-07-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_created_by_campaign_created_on'),
        ('maps', '0002_rename_world_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
            preserve_default=False,
        ),
    ]
