# Generated by Django 4.0.6 on 2022-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_map_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='order',
            field=models.IntegerField(default=1, help_text='Used for ordering of the maps in the UI'),
        ),
    ]
