# Generated by Django 4.0.6 on 2022-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_map_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='tile_scale',
            field=models.IntegerField(default=1, help_text='Used to scale the world. Default scale is 5x5'),
        ),
    ]
