# Generated by Django 4.0.6 on 2022-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_map_tile_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='tile_size',
            field=models.IntegerField(default=10, help_text='Used to scale the individual tile size in the UI.'),
        ),
    ]
