# Generated by Django 4.0.6 on 2022-07-28 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_created_by_campaign_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0006_map_tile_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='WorldMap',
        ),
    ]
