# Generated by Django 4.0.6 on 2022-07-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_imageasset_asset'),
        ('maps', '0007_rename_map_worldmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldMapAssetThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cb_path', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
        migrations.AddField(
            model_name='worldmap',
            name='assets',
            field=models.ManyToManyField(through='maps.WorldMapAssetThrough', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='worldmapassetthrough',
            name='world_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.worldmap'),
        ),
    ]
