# Generated by Django 4.0.6 on 2022-07-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_worldmapassetthrough_worldmap_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldmapassetthrough',
            name='layer_uuid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
