# Generated by Django 4.0.6 on 2022-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_worldmapassetthrough_layer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldmapassetthrough',
            name='asset_meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
