version: '3'

networks:
  app-tier:
    ipam:
      config:
        - subnet: 172.23.0.0/24

services:
 web:
  build: .
  volumes:
   - .:/usr/src/app
  container_name: dndweb_local
  tty: true
  ports:
   - 8000:8000
   - 3000-3100:3000-3100
   - 3000-3100:3000-3100/udp
  environment:
   - ENVIRONMENT=local
   - POSTGRES_DB=dndweb
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  command: /usr/src/app/run.sh
  depends_on:
    - memcached
    - db
    # - dndapi
  networks:
    - app-tier
 db:
  image: postgres
  container_name: db
  volumes:
   - ../dndpostgresdata/db:/var/lib/postgresql/data
  environment:
   - POSTGRES_DB=dndweb
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  ports:
    - 5432:5432
  networks:
      - app-tier
 memcached:
  image: 'bitnami/memcached:latest'
  ports:
    - 11211:11211
  networks:
      - app-tier

 # dnddb:
 #  image: ghcr.io/5e-bits/5e-database:latest
 #  ports:
 #    - "27017:27017"
 #  networks:
 #      - app-tier
 # dndcache:
 #  image: redis:6.2.5
 #  ports:
 #    - "6379:6379"
 #  networks:
 #    - app-tier
 # dndapi:
 #   environment:
 #     MONGODB_URI: mongodb://dnddb/5e-database
 #     REDIS_URL: redis://dndcache:6379
 #     PORT: 8001
 #   build: ../5e-srd-api/
 #   ports:
 #     - '8001:8001'
 #   depends_on:
 #     - dnddb
 #     - dndcache
 #   networks:
 #      - app-tier