# Generated by Django 4.0.6 on 2022-07-28 19:32

import assets.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_created_by_campaign_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('layer_uuid', models.UUIDField(blank=True, null=True)),
                ('asset', models.FileField(blank=True, null=True, upload_to=assets.models.asset_upload_to)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
