# Generated by Django 4.0.6 on 2022-07-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
