# Generated by Django 4.0.6 on 2022-07-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_imageasset_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageasset',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='imageasset',
            name='layer_uuid',
        ),
    ]
