# Generated by Django 4.0.6 on 2022-07-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_imageasset_campaign_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageAsset',
            new_name='Asset',
        ),
    ]
