# Generated by Django 4.0.6 on 2022-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_imageasset_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
