# Generated by Django 4.0.6 on 2022-07-27 15:59

import campaigns.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=campaigns.models.campaign_banner_upload_to)),
                ('dungeon_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_dungeon_master', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='campaign_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
